removing subsample_file_path function, see note below
previous migration file will need to be edited to remove it as a reference else you'll get the following error creating subsequent migrations:
 AttributeError: 'module' object has no attribute 'subsample_file_path'